# -*- coding: utf-8 -*-
"""MultiOutputDPV_PyTorch_ManuscriptVersion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ktUuQs0H78MsANvkDvi2A0eLKFalTYoN
"""

# Commented out IPython magic to ensure Python compatibility.
# %reset -f

import torch
import torch.nn as nn
import torch.optim as optim

"""# Define functions"""

def importfile(file_path):
    import numpy as np
    import csv

    # required format: 1st row = voltage; rest of rows = current values
    with open(file_path, newline='') as csvfile:
        data = list(csv.reader(csvfile))

        numpy_array_data = np.array(data)  # convert to numpy array
        print('full data set: with headers')
        print(numpy_array_data)

        # truncate 1st row (headers)
        data_trunc = np.float32(numpy_array_data[1:,:])
        print('truncated data set: no headers')
        print(data_trunc)
        print(np.shape(data_trunc))

    # return data with no headers, data with headers
    return data_trunc, numpy_array_data

def normalize_data_to_max(dpv_datagroup_withheaders):
    volts = np.float32(dpv_datagroup_withheaders[0,:])  # extract volts from first row of input data
    dpv_datagroup_normalized = np.empty(np.shape(dpv_datagroup_withheaders))  # make empty array
    dpv_datagroup_normalized[0,:] = volts  # set first row of the new dataset to volts

    for i in range(1, np.shape(dpv_datagroup_withheaders)[0]):
        dpv_datagroup_normalized[i,:] = np.float32( dpv_datagroup_withheaders[i,:] / np.max(dpv_datagroup_withheaders[i,:]) )

        plt.figure(1)
        plt.plot(volts, dpv_datagroup_normalized[i,:])
        plt.xlabel('V vs Ag/AgCl')
        plt.ylabel('Normalized Current (i/i_max)')

    return dpv_datagroup_normalized

def NMF_process(data, num_endmembers):
    import matplotlib
    import matplotlib.pyplot as plt
    import seaborn as sns
    from sklearn.decomposition import NMF
    from random import randint

    # shave off the first row (attributed to voltage values)
    ydata = data[1:, :]

    # use NMF
    model = NMF(n_components = num_endmembers, init='random', random_state=randint(0, 1000), max_iter = 1000)
    endmembers = model.fit(ydata).components_ # X in our equation
    abundances = model.transform(ydata) # beta in our equation

    # determine shape of data
    dims = np.shape(ydata)

    # call out voltage (first row)
    volts = np.float32(data[0,:])

    # plot the results
    plt.figure(1)
    v = np.reshape(volts, (1, dims[1]))
    plt.plot(v.T, endmembers.T)
    plt.xlabel('V vs Ag/AgCl')
    #labels = ['E1','E2']
    #plt.legend(labels)

    # Run these steps a few times until you see a significant change.
    # The endmembers change on each run!

    #%% plot endmembers
    plt.figure(2)
    plt.clf()

    for i in range(0, num_endmembers):
        plt.subplot(2,2,i+1)
        plt.plot(v[0,:], endmembers[i,:])
        plt.xlabel('V vs Ag/AgCl')
        plt.title('E' + str(i+1))
        plt.tight_layout()

    return model, abundances, endmembers, v

# caution: this only works with data that has three endmembers
def decompose_NMF3(dpv_datagroup, abundances, endmembers, volts):
    # decompose data

    component_arrays_concatenated_all = np.empty((np.shape(dpv_datagroup)[0], np.shape(dpv_datagroup)[1] * 4))
    for i in range(0,np.shape(dpv_datagroup)[0]):
        fig = plt.figure(1)
        fig.set_figheight(20)
        fig.set_figwidth(15)

        plt.subplot(15,15,i+1)
        e1 = abundances[i,0] * endmembers[0,:]
        e2 = abundances[i,1] * endmembers[1,:]
        e3 = abundances[i,2] * endmembers[2,:]

        plt.plot(volts[0,:], dpv_datagroup[i,:], 'k')
        plt.plot(volts[0,:], e1)
        plt.plot(volts[0,:], e2)
        plt.plot(volts[0,:], e3)

        plt.ylabel('current (A)', fontsize=5)
        plt.xlabel('voltage (V vs. Ag/AgCl)', fontsize=5)
        plt.xticks(fontsize = 5)
        plt.yticks(fontsize = 5)

        rawdata = dpv_datagroup[i,:]

        # horizontally concatenates all the data; will become a 1D vector
        component_arrays = [rawdata.T, e1.T, e2.T, e3.T]
        component_arrays_concatenated1 = np.hstack((rawdata.T, e1.T))
        component_arrays_concatenated2 = np.hstack((component_arrays_concatenated1, e2.T))
        component_arrays_concatenated3 = np.hstack((component_arrays_concatenated2, e3.T))

        component_arrays_concatenated3 = np.reshape(component_arrays_concatenated3, (1, np.shape(component_arrays_concatenated3)[0]))
        component_arrays_concatenated_all[i,:] = np.float32((component_arrays_concatenated3))

    return component_arrays, component_arrays_concatenated_all

# caution: this only works with data that has four endmembers
def decompose_NMF4(dpv_datagroup, abundances, endmembers, volts):
    # decompose data

    component_arrays_concatenated_all = np.empty((np.shape(dpv_datagroup)[0], np.shape(dpv_datagroup)[1] * 5))
    for i in range(0,np.shape(dpv_datagroup)[0]):
        fig = plt.figure(1)
        fig.set_figheight(25)
        fig.set_figwidth(20)

        plt.subplot(17,17,i+1)
        e1 = abundances[i,0] * endmembers[0,:]
        e2 = abundances[i,1] * endmembers[1,:]
        e3 = abundances[i,2] * endmembers[2,:]
        e4 = abundances[i,3] * endmembers[3,:]

        plt.plot(volts[0,:], dpv_datagroup[i,:], 'k')
        plt.plot(volts[0,:], e1)
        plt.plot(volts[0,:], e2)
        plt.plot(volts[0,:], e3)
        plt.plot(volts[0,:], e4)

        plt.ylabel('current (A)', fontsize=5)
        plt.xlabel('voltage (V vs. Ag/AgCl)', fontsize=5)
        plt.xticks(fontsize = 5)
        plt.yticks(fontsize = 5)

        rawdata = dpv_datagroup[i,:]

        # horizontally concatenates all the data; will become a 1D vector
        component_arrays = [rawdata.T, e1.T, e2.T, e3.T, e4.T]
        component_arrays_concatenated1 = np.hstack((rawdata.T, e1.T))
        component_arrays_concatenated2 = np.hstack((component_arrays_concatenated1, e2.T))
        component_arrays_concatenated3 = np.hstack((component_arrays_concatenated2, e3.T))
        component_arrays_concatenated4 = np.hstack((component_arrays_concatenated3, e4.T))

        component_arrays_concatenated4 = np.reshape(component_arrays_concatenated4, (1, np.shape(component_arrays_concatenated4)[0]))
        component_arrays_concatenated_all[i,:] = np.float32((component_arrays_concatenated4))

    return component_arrays, component_arrays_concatenated_all

# caution: this only works with data that has four endmembers
def decompose_NMF4_edit(dpv_datagroup, abundances, endmembers, volts):
    # decompose data

    component_arrays_concatenated_all = np.empty((np.shape(dpv_datagroup)[0], np.shape(dpv_datagroup)[1] * 5))
    for i in range(0,np.shape(dpv_datagroup)[0]):

        fig = plt.figure(1)
        fig.set_figheight(25)
        fig.set_figwidth(20)

        plt.subplot(17,17,i+1)

        e1 = abundances[i,0] * endmembers[0,:]
        e2 = abundances[i,1] * endmembers[1,:]
        e3 = abundances[i,2] * endmembers[2,:]
        e4 = abundances[i,3] * endmembers[3,:]

        #plt.plot(volts[0,:], dpv_datagroup[i,:], 'k')
        plt.plot(volts[0,:], e1)
        plt.plot(volts[0,:], e2)
        plt.plot(volts[0,:], e3)
        plt.plot(volts[0,:], e4)

        plt.ylabel('current (A)', fontsize=5)
        plt.xlabel('voltage (V vs. Ag/AgCl)', fontsize=5)
        plt.xticks(fontsize = 5)
        plt.yticks(fontsize = 5)

        rawdata = dpv_datagroup[i,:]

        # horizontally concatenates all the data; will become a 1D vector
        component_arrays = [rawdata.T, e1.T, e2.T, e3.T, e4.T]
        component_arrays_concatenated1 = np.hstack((rawdata.T, e1.T))
        component_arrays_concatenated2 = np.hstack((component_arrays_concatenated1, e2.T))
        component_arrays_concatenated3 = np.hstack((component_arrays_concatenated2, e3.T))
        component_arrays_concatenated4 = np.hstack((component_arrays_concatenated3, e4.T))

        component_arrays_concatenated4 = np.reshape(component_arrays_concatenated4, (1, np.shape(component_arrays_concatenated4)[0]))
        component_arrays_concatenated_all[i,:] = np.float32((component_arrays_concatenated4))

    return component_arrays, component_arrays_concatenated_all

"""# Import DPVs"""

# import datasets (as numpy array dtype)
import numpy as np
import csv
import matplotlib.pyplot as plt


csv_file_path = '251020_MNGE_IAA_trp_titrations_data_to_ML.csv'
data_trunc1, numpy_array_data1 = importfile(csv_file_path)

csv_file_path2 = '250521_Pchl698_S00-S43_all_DPVs_transposed.csv'
data_trunc2, numpy_array_data2 = importfile(csv_file_path2)

# truncate dataset to remove last three column outputs (the labels); keep headers
len(data_trunc1)
data_trunc1_no_outputs = numpy_array_data1[:, 0:300]
print('training data, no label outputs, headers retained')
print(np.shape(data_trunc1_no_outputs))

# truncate dataset to remove headers and last two columns
data_trunc1_no_outputs_no_header = data_trunc1[:, 0:300]
print('training data, no outputs, no headers')
print(np.shape(data_trunc1_no_outputs_no_header))

# truncate dataset to remove headers only
data_trunc1_no_header = numpy_array_data1[1:, :]
print('training data, no headers')
print(np.shape(data_trunc1_no_header))

# COMBINE training data and sample data into single numpy array --> this is to do NMF decomposition
combined_training_sample_dataset = np.vstack((data_trunc1_no_outputs, data_trunc2))
print(np.shape(combined_training_sample_dataset))

# remove headers from combined dataset
print(np.shape(combined_training_sample_dataset[1:,:]))
print(combined_training_sample_dataset[1:,:])

combined_training_sample_dataset_no_outputs_no_header = combined_training_sample_dataset[1:,0:300]
print(np.shape(combined_training_sample_dataset_no_outputs_no_header))

# run NMF on combined training/sample dataset
model0, abundances0, endmembers0, volts0 = NMF_process(combined_training_sample_dataset, num_endmembers=4)

decomp0, decomp0_1Dvector = decompose_NMF4_edit(combined_training_sample_dataset_no_outputs_no_header, abundances0, endmembers0, volts0)
print(np.shape(decomp0_1Dvector))

# generate a validation set: train/test split
from sklearn.model_selection import train_test_split

# standards training data only
extract_decomp0_1Dvector = decomp0_1Dvector[0:np.shape(data_trunc1_no_header)[0],:]  # extract decomposed data (stds only) from the whole decomposition matrix
print('extract stds training data')
print(np.shape(extract_decomp0_1Dvector))

# put outputs back on **hardcoded**
data_trunc1_no_header_outputs_only = numpy_array_data1[1:, 300:303]  # call all the output data related to the stds (extract from numpy_array_data1 <- initially imported stds)
extract_decomp0_1Dvector_w_outputs = np.hstack((extract_decomp0_1Dvector, data_trunc1_no_header_outputs_only))
print('extract stds training data, with outputs')
print(np.shape(extract_decomp0_1Dvector_w_outputs))

xytrain, xytest = train_test_split(extract_decomp0_1Dvector_w_outputs, test_size = 0.1)
print('train/test split size')
print(np.shape(xytrain))
print(np.shape(xytest))

# splitting the standards data into a train/test set
data_trunc1_train = np.array(xytrain, dtype=float)
data_trunc1_test = np.array(xytest, dtype=float)
print('train/test split')
print(data_trunc1_train)
print(data_trunc1_test)

"""# Train model on combined training dataset"""

# define model
class MultiOutputRegressor(nn.Module):
    def __init__(self, input_dim, output_dim):
        super(MultiOutputRegressor, self).__init__()
        self.fc1 = nn.Linear(input_dim, 128)
        self.fc2 = nn.Linear(128, 64)
        self.fc3 = nn.Linear(64, 32)
        self.fc4 = nn.Linear(32, output_dim)

    def forward(self, x):
        x = torch.relu(self.fc1(x))
        x = torch.relu(self.fc2(x))
        x = torch.relu(self.fc3(x))
        x = self.fc4(x)
        return x

# loop over NN generation; average the predictions
all_predictions = np.empty((np.shape(data_trunc2)[0]-1, 3))  # empty vector to store predictions in
all_root_mean_squared_error = np.empty((1,))
all_mean_absolute_error = np.empty((1,))

from sklearn.metrics import mean_squared_error, mean_absolute_error, root_mean_squared_error
for i in range(0,200):

    # build model (edit these fields)
    input_dim = 1500  # input dimension: be sure to manually adjust this value!!
    output_dim = 3  # output dimension: be sure to manually adjust this value!!

    # data to input (edit these fields)
    decomposed1Dvector_for_trainingset = data_trunc1_train[:,0:input_dim]   # training stds only, no samples
    print('size of training set, no outputs')
    print(np.shape(decomposed1Dvector_for_trainingset))

    # recall the training set that was split off earlier
    np_xytrain = np.array(data_trunc1_train[:, np.shape(data_trunc1_train)[1]-output_dim : np.shape(data_trunc1_train)[1]], dtype=float)
    print('ground truth for training set')
    print(np_xytrain)

    model = MultiOutputRegressor(input_dim, output_dim)
    criterion = nn.MSELoss()
    #optimizer = optim.Adam(model.parameters(), lr=0.001)
    optimizer = optim.AdamW(model.parameters(), lr=0.0002)

    # training data (with full dataset)
    X_train = torch.tensor(decomposed1Dvector_for_trainingset[:,0:input_dim]).float()
    y_train = torch.tensor(np_xytrain).float()

    num_epochs = 6500
    for epoch in range(num_epochs):
        model.train()
        optimizer.zero_grad()

        outputs = model(X_train)
        #print(outputs)
        loss = criterion(outputs, y_train)

        loss.backward()
        optimizer.step()

        if (epoch+1) % 100 == 0:
            print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}')

    # test the model with the sample data!
    decomp0_1Dvector_scaled = np.multiply(decomp0_1Dvector[145:,:], 1.5)  # scale the data by factor indicated...
    print(decomp0_1Dvector_scaled)

    model.eval()
    with torch.no_grad():
        X_test = torch.tensor(decomp0_1Dvector_scaled[:, 0:input_dim]).float()  # test data
        predictions = model(X_test)
        #print(predictions)

        np.set_printoptions(suppress=True)
        np_predictions = np.array(predictions)
        print(np_predictions)

    all_predictions = np.hstack((all_predictions, np_predictions))  # store predictions in a numpy array
    print(np.shape(all_predictions))


    # test the model on the validation set

    # ground truth --> y_test is the last three columns of data_trunc1_test
    y_validate = torch.tensor(data_trunc1_test[:, np.shape(data_trunc1_test)[1]-output_dim : np.shape(data_trunc1_test)[1]]).float()

    # make predictions from model
    x_val = data_trunc1_test[:,0:input_dim]
    x_validate = torch.tensor(x_val).float()
    predictions_xvalidate = model(x_validate)
    np_predictions_xtest = predictions_xvalidate.detach().numpy()

    # Calculate MSE and MAE
    rmse = root_mean_squared_error(y_validate.numpy()[:,1], np_predictions_xtest[:,1])  # choose the middle column only for IAA
    mae = mean_absolute_error(y_validate.numpy()[:,1], np_predictions_xtest[:,1])

    print(f'Root Mean Squared Error on Test Data: {rmse:.4f}')
    print(f'Mean Absolute Error on Test Data: {mae:.4f}')

    all_root_mean_squared_error = np.hstack((all_root_mean_squared_error, rmse))  # store rmse in a numpy array
    all_mean_absolute_error = np.hstack((all_mean_absolute_error, mae))  # store mae in a numpy array

"""# post-training, model evaluation math"""

print(np.reshape(all_root_mean_squared_error, (np.shape(all_root_mean_squared_error)[0], 1)))
print(np.reshape(all_mean_absolute_error, (np.shape(all_mean_absolute_error)[0], 1)))

print('avg rmse across all iterations')
print(np.mean(all_root_mean_squared_error[1:]))

print('avg mae across all iterations')
print(np.mean(all_mean_absolute_error[1:]))

# average iaa concs (column 2) across all predictions
print(np.shape(all_predictions))
print(all_predictions)

# take abs value
all_predictions_abs = np.abs(all_predictions)

iaa_concs = all_predictions_abs[:, 4:np.shape(all_predictions)[1]:3]  # calls only the iaa predicted column

print(np.shape(iaa_concs))
print(iaa_concs)

iaa_concs_row_avg = np.mean(iaa_concs, axis=1)
iaa_concs_row_med = np.median(iaa_concs, axis=1)
iaa_concs_row_std = np.std(iaa_concs, axis=1)

iaa_concs_row_avg_reshaped = np.reshape(iaa_concs_row_avg, (np.shape(iaa_concs_row_avg)[0], 1))
iaa_concs_row_med_reshaped = np.reshape(iaa_concs_row_med, (np.shape(iaa_concs_row_med)[0], 1))
iaa_concs_row_std_reshaped = np.reshape(iaa_concs_row_std, (np.shape(iaa_concs_row_std)[0], 1))
print('avged data')
print(iaa_concs_row_avg_reshaped)
print('med data')
print(iaa_concs_row_med_reshaped)
print('std data')
print(iaa_concs_row_std_reshaped)

# remove outliers, take data only within 1 std dev from mean
def remove_outliers_zscore(data, threshold):
    mean = np.mean(data)
    std = np.std(data)
    z_scores = (data - mean) / std
    return data[np.abs(z_scores) < threshold]

def remove_outliers_zscore_median(data, threshold):
    median = np.median(data)
    std = np.std(data)
    z_scores = (data - median) / std
    return data[np.abs(z_scores) < threshold]

iaa_concs_new_avg = np.empty((np.shape(iaa_concs)[0], 1))
iaa_concs_new_std = np.empty((np.shape(iaa_concs)[0], 1))
for i in range(0, np.shape(iaa_concs)[0]):
    single_row_iaa = iaa_concs[i,:]
    single_row_iaa_no_outliers = remove_outliers_zscore_median(single_row_iaa, 2)
    #print(single_row_iaa_no_outliers)
    new_row_avg = np.mean(single_row_iaa_no_outliers)
    new_row_std = np.std(single_row_iaa_no_outliers)
    #print(new_row_avg)
    iaa_concs_new_avg[i] = new_row_avg
    iaa_concs_new_std[i] = new_row_std

np.reshape(iaa_concs_new_avg, (np.shape(iaa_concs_new_avg)[0], 1))
np.reshape(iaa_concs_new_std, (np.shape(iaa_concs_new_std)[0], 1))

print(iaa_concs_new_avg)
print(iaa_concs_new_std)